providers:
  google:
    logo: "google.png"
    color: "#34A853"
  poolside:
    logo: "poolside.png"
    color: "#4337FF"
  minimax:
    logo: "minimax.png"
    color: "#FF4074"
  z-ai:
    logo: "zai.png"
    color: "#0ea5e9"
  thinkingmachines:
    logo: "thinkingmachines.png"
    color: "#aaaaaa"
  qwen:
    logo: "qwen.png"
    color: "#7c3aed"
  anthropic:
    logo: "claude.png"
    color: "#d97757"
  openai:
    logo: "chatgpt.png"
    color: "#10a37f"
  moonshotai:
    logo: "kimi.png"
    color: "#1783FF"
  deepseek:
    logo: "deepseek.png"
    color: "#4D6BFE"
  meta:
    logo: "meta.png"
    color: "#0082FB"
  x-ai:
    logo: "xai.png"
    color: "#000000"